In [2]:
import tensorflow as tf

In [3]:
my_data = [
    [0, 1,],
    [2, 3,],
    [4, 5,],
    [6, 7,],
]

In [4]:
slices = tf.data.Dataset.from_tensor_slices(my_data)

In [7]:
print(slices)

<TensorSliceDataset shapes: (2,), types: tf.int32>


In [9]:
next_item = slices.make_one_shot_iterator().get_next()

In [11]:
session = tf.Session()
while True:
    print(session.run(next_item))

[0 1]
[2 3]
[4 5]
[6 7]


OutOfRangeError: End of sequence
	 [[Node: IteratorGetNext_1351 = IteratorGetNext[output_shapes=[[2]], output_types=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_1352)]]

Caused by op 'IteratorGetNext_1351', defined at:
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 127, in start
    self.asyncio_loop.run_forever()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 421, in run_forever
    self._run_once()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1431, in _run_once
    handle._run()
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 117, in _handle_events
    handler_func(fileobj, events)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 450, in _handle_events
    self._handle_recv()
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 480, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/zmq/eventloop/zmqstream.py", line 432, in _run_callback
    callback(*args, **kwargs)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/tornado/stack_context.py", line 276, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2903, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-9-8ceae87e71b2>", line 1, in <module>
    next_item = slices.make_one_shot_iterator().get_next()
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/tensorflow/python/data/ops/iterator_ops.py", line 370, in get_next
    name=name)), self._output_types,
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/tensorflow/python/ops/gen_dataset_ops.py", line 1466, in iterator_get_next
    output_shapes=output_shapes, name=name)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3392, in create_op
    op_def=op_def)
  File "/Users/nikhilkuria/Dev/git/ml-mastery/_env/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1718, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

OutOfRangeError (see above for traceback): End of sequence
	 [[Node: IteratorGetNext_1351 = IteratorGetNext[output_shapes=[[2]], output_types=[DT_INT32], _device="/job:localhost/replica:0/task:0/device:CPU:0"](OneShotIterator_1352)]]


In [13]:
r = tf.random_normal([10,3])
print(session.run(r))

[[-0.01767031 -0.4748007   0.1120059 ]
 [-0.5836402  -0.01599916  0.0388441 ]
 [ 0.09299984  0.92972034 -0.9235901 ]
 [-0.435298    1.2730242   2.7217615 ]
 [ 1.9744501   0.6035711  -0.72449297]
 [ 1.1168827  -0.17859793  0.08521996]
 [ 1.8228045   0.5926449  -0.6529698 ]
 [-0.28283858  0.22039878 -0.94514537]
 [ 1.355885   -1.1072588  -2.2923143 ]
 [ 1.4645936   0.51793164  0.5567086 ]]


In [21]:
features = {
    'sales' : [[5], [10], [8], [9]],
    'department': ['sports', 'sports', 'gardening', 'gardening']}

department_column = tf.feature_column.categorical_column_with_vocabulary_list(
        'department', ['sports', 'gardening'])
department_column = tf.feature_column.indicator_column(department_column)

columns = [
    tf.feature_column.numeric_column('sales'),
    department_column
]

inputs = tf.feature_column.input_layer(features, columns)

In [22]:
var_init = tf.global_variables_initializer()
table_init = tf.tables_initializer()
session.run((var_init, table_init))

(None, None)

In [23]:
session.run(inputs)

array([[ 1.,  0.,  5.],
       [ 1.,  0., 10.],
       [ 0.,  1.,  8.],
       [ 0.,  1.,  9.]], dtype=float32)